'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type LanguageCode = 'en' | 'es' | 'fr' | 'de' | 'it' | 'pt';

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
}

const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    welcomeBack: 'Welcome back',
    liveAccountOverview: 'Here is your live account overview and growth metrics.',
    active: 'Active',
    inactive: 'Inactive',
    activateAccount: 'Activate Account',
    refLinkTitle: 'Your Exclusive Referral Link',
    refLinkSub: 'Share to invite new members to your downline network',
    copy: 'Copy',
    copied: 'Copied!',
    totalAvailableBalance: 'Total Available Balance (Main + P2P)',
    mainWalletBalance: 'Main Wallet Balance',
    p2pBalance: 'P2P Balance',
    todaysRoi: "Today's ROI Income",
    totalRoi: 'Total ROI Income',
    totalLevelIncome: 'Total Level Income',
    totalRewardIncome: 'Total Reward Income',
    totalEarnings: 'Total Earnings',
    totalInvestments: 'Total Investments',
    totalP2pSent: 'Total P2P Sent',
    totalP2pReceived: 'Total P2P Received',
    totalWithdrawals: 'Total Withdrawals',
    directReferrals: 'Direct Referrals',
    totalTeamBusiness: 'Total Team Business',
    strongLegBusiness: 'Strong Leg Business',
    weakLegBusiness: 'Weak Leg Business',
    viewWallet: 'View Wallet →',
    depositFunds: 'Deposit Funds',
    activateInvestment: 'Activate Investment',
    p2pTransfer: 'P2P Transfer',
    withdrawEarnings: 'Withdraw Earnings',
    recentTransactions: 'Recent Transactions',
    viewAll: 'View All →',
    home: 'Home',
    incomePlan: 'Income Plan',
    howItWorks: 'How It Works',
    faq: 'FAQ',
    contact: 'Contact',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    accountSettings: 'Account Settings',
    securityPin: 'Security & PIN',
    changePassword: 'Change Password',
    systemInvestments: 'System Investments',
    promotions: 'Promotions',
    userManagement: 'User Management',
    adminDashboard: 'Admin Dashboard',
    financialOps: 'FINANCIAL OPS',
    networkTeam: 'NETWORK & TEAM',
    core: 'CORE',
  },
  es: {
    dashboard: 'Tablero',
    welcomeBack: 'Bienvenido de nuevo',
    liveAccountOverview: 'Aquí está el resumen de su cuenta y métricas de crecimiento.',
    active: 'Activo',
    inactive: 'Inactivo',
    activateAccount: 'Activar Cuenta',
    refLinkTitle: 'Su Enlace Exclusivo de Referido',
    refLinkSub: 'Comparta para invitar a nuevos miembros a su red',
    copy: 'Copiar',
    copied: '¡Copiado!',
    totalAvailableBalance: 'Saldo Disponible Total (Principal + P2P)',
    mainWalletBalance: 'Saldo de Billetera Principal',
    p2pBalance: 'Saldo P2P',
    todaysRoi: 'Ingresos ROI de Hoy',
    totalRoi: 'Ingresos ROI Totales',
    totalLevelIncome: 'Ingresos por Nivel Totales',
    totalRewardIncome: 'Ingresos por Recompensas',
    totalEarnings: 'Ganancias Totales',
    totalInvestments: 'Inversiones Totales',
    totalP2pSent: 'Total P2P Enviado',
    totalP2pReceived: 'Total P2P Recibido',
    totalWithdrawals: 'Retiros Totales',
    directReferrals: 'Referidos Directos',
    totalTeamBusiness: 'Volumen Total de Equipo',
    strongLegBusiness: 'Negocio de Pierna Fuerte',
    weakLegBusiness: 'Negocio de Pierna Débil',
    viewWallet: 'Ver Billetera →',
    depositFunds: 'Depositar Fondos',
    activateInvestment: 'Activar Inversión',
    p2pTransfer: 'Transferencia P2P',
    withdrawEarnings: 'Retirar Ganancias',
    recentTransactions: 'Transacciones Recientes',
    viewAll: 'Ver Todo →',
    home: 'Inicio',
    incomePlan: 'Plan de Ingresos',
    howItWorks: 'Cómo Funciona',
    faq: 'Preguntas Frecuentes',
    contact: 'Contacto',
    login: 'Iniciar Sesión',
    register: 'Registrarse',
    logout: 'Cerrar Sesión',
    accountSettings: 'Configuración',
    securityPin: 'Seguridad y PIN',
    changePassword: 'Cambiar Contraseña',
    systemInvestments: 'Inversiones del Sistema',
    promotions: 'Promociones',
    userManagement: 'Gestión de Usuarios',
    adminDashboard: 'Tablero de Admin',
    financialOps: 'OPERACIONES FINANCIERAS',
    networkTeam: 'RED Y EQUIPO',
    core: 'PRINCIPAL',
  },
  fr: {
    dashboard: 'Tableau de bord',
    welcomeBack: 'Bon retour',
    liveAccountOverview: 'Voici votre aperçu de compte en direct et métriques de croissance.',
    active: 'Actif',
    inactive: 'Inactif',
    activateAccount: 'Activer le Compte',
    refLinkTitle: 'Votre Lien de Parrainage Exclusif',
    refLinkSub: 'Partagez pour inviter de nouveaux membres à votre réseau',
    copy: 'Copier',
    copied: 'Copié !',
    totalAvailableBalance: 'Solde Disponible Total (Principal + P2P)',
    mainWalletBalance: 'Solde du Portefeuille Principal',
    p2pBalance: 'Solde P2P',
    todaysRoi: "Revenu ROI d'Aujourd'hui",
    totalRoi: 'Revenu ROI Total',
    totalLevelIncome: 'Revenu de Niveau Total',
    totalRewardIncome: 'Revenu des Récompenses',
    totalEarnings: 'Gains Totaux',
    totalInvestments: 'Investissements Totaux',
    totalP2pSent: 'Total P2P Envoyé',
    totalP2pReceived: 'Total P2P Reçu',
    totalWithdrawals: 'Retraits Totaux',
    directReferrals: 'Parrainages Directs',
    totalTeamBusiness: "Volume d'Équipe Total",
    strongLegBusiness: 'Affaires Patte Forte',
    weakLegBusiness: 'Affaires Patte Faible',
    viewWallet: 'Voir Portefeuille →',
    depositFunds: 'Déposer des Fonds',
    activateInvestment: 'Activer Investissement',
    p2pTransfer: 'Transfert P2P',
    withdrawEarnings: 'Retirer Gains',
    recentTransactions: 'Transactions Récentes',
    viewAll: 'Voir Tout →',
    home: 'Accueil',
    incomePlan: 'Plan de Revenus',
    howItWorks: 'Comment Ça Marche',
    faq: 'FAQ',
    contact: 'Contact',
    login: 'Connexion',
    register: "S'inscrire",
    logout: 'Déconnexion',
    accountSettings: 'Paramètres du Compte',
    securityPin: 'Sécurité et PIN',
    changePassword: 'Changer le Mot de Passe',
    systemInvestments: 'Investissements Système',
    promotions: 'Promotions',
    userManagement: 'Gestion des Utilisateurs',
    adminDashboard: "Tableau d'Administration",
    financialOps: 'OPÉRATIONS FINANCIÈRES',
    networkTeam: 'RÉSEAU ET ÉQUIPE',
    core: 'CORE',
  },
  de: {
    dashboard: 'Dashboard',
    welcomeBack: 'Willkommen zurück',
    liveAccountOverview: 'Hier ist Ihre Live-Kontoübersicht und Wachstumskennzahlen.',
    active: 'Aktiv',
    inactive: 'Inaktiv',
    activateAccount: 'Konto Aktivieren',
    refLinkTitle: 'Ihr Exklusiver Empfehlungslink',
    refLinkSub: 'Teilen Sie ihn, um neue Mitglieder in Ihr Netzwerk einzuladen',
    copy: 'Kopieren',
    copied: 'Kopiert!',
    totalAvailableBalance: 'Verfügbares Gesamtguthaben (Haupt + P2P)',
    mainWalletBalance: 'Haupt-Guthaben',
    p2pBalance: 'P2P-Guthaben',
    todaysRoi: 'Heutiges ROI-Einkommen',
    totalRoi: 'Gesamtes ROI-Einkommen',
    totalLevelIncome: 'Gesamtes Stufeneinkommen',
    totalRewardIncome: 'Belohnungseinkommen',
    totalEarnings: 'Gesamteinnahmen',
    totalInvestments: 'Gesamtinvestitionen',
    totalP2pSent: 'Gesamt P2P Gesendet',
    totalP2pReceived: 'Gesamt P2P Empfangen',
    totalWithdrawals: 'Gesamtabhebungen',
    directReferrals: 'Direkte Empfehlungen',
    totalTeamBusiness: 'Gesamtes Team-Volumen',
    strongLegBusiness: 'Starkes Bein Geschäft',
    weakLegBusiness: 'Schwaches Bein Geschäft',
    viewWallet: 'Guthaben anzeigen →',
    depositFunds: 'Guthaben einzahlen',
    activateInvestment: 'Investition aktivieren',
    p2pTransfer: 'P2P-Überweisung',
    withdrawEarnings: 'Einnahmen abheben',
    recentTransactions: 'Letzte Transaktionen',
    viewAll: 'Alle anzeigen →',
    home: 'Startseite',
    incomePlan: 'Einkommensplan',
    howItWorks: 'Wie es funktioniert',
    faq: 'FAQ',
    contact: 'Kontakt',
    login: 'Anmelden',
    register: 'Registrieren',
    logout: 'Abmelden',
    accountSettings: 'Konto-Einstellungen',
    securityPin: 'Sicherheit & PIN',
    changePassword: 'Passwort ändern',
    systemInvestments: 'System-Investitionen',
    promotions: 'Aktionen',
    userManagement: 'Benutzerverwaltung',
    adminDashboard: 'Admin-Dashboard',
    financialOps: 'FINANZOPERATIONEN',
    networkTeam: 'NETZWERK & TEAM',
    core: 'KERN',
  },
  it: {
    dashboard: 'Dashboard',
    welcomeBack: 'Bentornato',
    liveAccountOverview: 'Ecco la panoramica del tuo conto in tempo reale.',
    active: 'Attivo',
    inactive: 'Inattivo',
    activateAccount: 'Attiva Conto',
    refLinkTitle: 'Il Tuo Link Referral Esclusivo',
    refLinkSub: 'Condividi per invitare nuovi membri nella tua rete',
    copy: 'Copia',
    copied: 'Copiato!',
    totalAvailableBalance: 'Saldo Totale Disponibile (Principale + P2P)',
    mainWalletBalance: 'Saldo Portafoglio Principale',
    p2pBalance: 'Saldo P2P',
    todaysRoi: 'Entrate ROI di Oggi',
    totalRoi: 'Entrate ROI Totali',
    totalLevelIncome: 'Entrate per Livello Totali',
    totalRewardIncome: 'Entrate da Ricompense',
    totalEarnings: 'Guadagni Totali',
    totalInvestments: 'Investimenti Totali',
    totalP2pSent: 'Totale P2P Inviato',
    totalP2pReceived: 'Totale P2P Ricevuto',
    totalWithdrawals: 'Prelievi Totali',
    directReferrals: 'Referral Diretti',
    totalTeamBusiness: 'Volume Totale di Squadra',
    strongLegBusiness: 'Volume Gamba Forte',
    weakLegBusiness: 'Volume Gamba Debole',
    viewWallet: 'Visualizza Portafoglio →',
    depositFunds: 'Deposita Fondi',
    activateInvestment: 'Attiva Investimento',
    p2pTransfer: 'Trasferimento P2P',
    withdrawEarnings: 'Preleva Guadagni',
    recentTransactions: 'Transazioni Recenti',
    viewAll: 'Vedi Tutti →',
    home: 'Home',
    incomePlan: 'Piano Guadagni',
    howItWorks: 'Come Funziona',
    faq: 'FAQ',
    contact: 'Contatti',
    login: 'Accedi',
    register: 'Registrati',
    logout: 'Disconnetti',
    accountSettings: 'Impostazioni Account',
    securityPin: 'Sicurezza e PIN',
    changePassword: 'Cambia Password',
    systemInvestments: 'Investimenti Sistema',
    promotions: 'Promozioni',
    userManagement: 'Gestione Utenti',
    adminDashboard: 'Dashboard Admin',
    financialOps: 'OPERAZIONI FINANZIARIE',
    networkTeam: 'RETE E SQUADRA',
    core: 'CORE',
  },
  pt: {
    dashboard: 'Painel',
    welcomeBack: 'Bem-vindo de volta',
    liveAccountOverview: 'Aqui está a visão geral da sua conta e métricas.',
    active: 'Ativo',
    inactive: 'Inativo',
    activateAccount: 'Ativar Conta',
    refLinkTitle: 'Seu Link de Indicação Exclusivo',
    refLinkSub: 'Compartilhe para convidar novos membros para sua rede',
    copy: 'Copiar',
    copied: 'Copiado!',
    totalAvailableBalance: 'Saldo Total Disponível (Principal + P2P)',
    mainWalletBalance: 'Saldo da Carteira Principal',
    p2pBalance: 'Saldo P2P',
    todaysRoi: 'Rendimento ROI de Hoje',
    totalRoi: 'Rendimento ROI Total',
    totalLevelIncome: 'Rendimento por Nível Total',
    totalRewardIncome: 'Rendimento de Recompensas',
    totalEarnings: 'Ganhos Totais',
    totalInvestments: 'Investimentos Totais',
    totalP2pSent: 'Total P2P Enviado',
    totalP2pReceived: 'Total P2P Recebido',
    totalWithdrawals: 'Saques Totais',
    directReferrals: 'Indicações Diretas',
    totalTeamBusiness: 'Volume Total da Equipe',
    strongLegBusiness: 'Volume Perna Forte',
    weakLegBusiness: 'Volume Perna Fraca',
    viewWallet: 'Ver Carteira →',
    depositFunds: 'Depositar Fundos',
    activateInvestment: 'Ativar Investimento',
    p2pTransfer: 'Transferência P2P',
    withdrawEarnings: 'Sacar Ganhos',
    recentTransactions: 'Transações Recentes',
    viewAll: 'Ver Tudo →',
    home: 'Início',
    incomePlan: 'Plano de Rendimentos',
    howItWorks: 'Como Funciona',
    faq: 'FAQ',
    contact: 'Contato',
    login: 'Entrar',
    register: 'Cadastrar',
    logout: 'Sair',
    accountSettings: 'Configurações da Conta',
    securityPin: 'Segurança e PIN',
    changePassword: 'Alterar Senha',
    systemInvestments: 'Investimentos do Sistema',
    promotions: 'Promoções',
    userManagement: 'Gestão de Usuários',
    adminDashboard: 'Painel Admin',
    financialOps: 'OPERAÇÕES FINANCEIRAS',
    networkTeam: 'REDE E EQUIPE',
    core: 'CORE',
  },
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key: string) => key,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>('en');

  useEffect(() => {
    const saved = localStorage.getItem('nexarise_app_language') as LanguageCode;
    if (saved && translations[saved]) {
      setLanguageState(saved);
    }

    const handleStorageChange = (e: StorageEvent) => {
      if (e.key === 'nexarise_app_language' && e.newValue && translations[e.newValue as LanguageCode]) {
        setLanguageState(e.newValue as LanguageCode);
      }
    };

    window.addEventListener('storage', handleStorageChange);
    return () => window.removeEventListener('storage', handleStorageChange);
  }, []);

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    localStorage.setItem('nexarise_app_language', lang);
    window.dispatchEvent(new Event('languageChange'));
  };

  useEffect(() => {
    const handleCustomEvent = () => {
      const saved = localStorage.getItem('nexarise_app_language') as LanguageCode;
      if (saved && translations[saved]) {
        setLanguageState(saved);
      }
    };
    window.addEventListener('languageChange', handleCustomEvent);
    return () => window.removeEventListener('languageChange', handleCustomEvent);
  }, []);

  const t = (key: string): string => {
    const langObj = translations[language] || translations.en;
    return langObj[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
